builds:
- env:
  - >-
    {{- if or (eq .Os "darwin") (eq .Os "windows") -}}
      CGO_ENABLED=1
    {{- else -}}
      CGO_ENABLED=0
    {{- end -}}
  goos:
  - {{ .Os }}
  - >-
    {{- if (eq .Os "linux") -}}
      freebsd
    {{- else -}}
  goarch:
    - amd64
    - arm64
    - '386'
  flags:
    - -trimpath
  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  disable: true
